---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ui-server
  namespace: kube-sms
  labels:
    run: ui
spec:
  rules:
    - host: sms.medinvention.dev
      http:
        paths:
          - backend:
              serviceName: ui-server-service
              servicePort: http
            path: /
  tls:
    - hosts:
      - sms.medinvention.dev
      secretName: sms-tls

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-server
  namespace: kube-sms
  labels:
    run: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ui
  template:
    metadata:
      labels:
        run: ui
    spec:
      containers:
        - name: ui-server
          image: medinvention/k8s-sms-ui
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "https://api-sms.medinvention.dev/"

---
apiVersion: v1
kind: Service
metadata:
  name: ui-server-service
  namespace: kube-sms
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    run: ui