apiVersion: v1
kind: ConfigMap
metadata:
  name: detail-server
  namespace: sample-sms
data:
  server: |
    from flask import Flask, json
    api = Flask(__name__)
    @api.route('/', methods=['GET'])
    def get():
      details = [{"id": 1, "name": "Detail One"}, {"id": 2, "name": "Detail Two"}]
      return json.dumps(details)
    if __name__ == '__main__':
      api.run()
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-detail
  namespace: sample-sms
  annotations:
    medinvention.dev/sms.group: detail
    medinvention.dev/sms.port: "5000"
    medinvention.dev/sms.service: detail-service
spec:
  selector:
    matchLabels:
      app: detail
  replicas: 1
  template:
    metadata:
      labels:
        app: detail
    spec:
      containers:
      - name: server
        image: python
        command: ['sh', '-c', 'pip install flask && python /var/static/server']
        ports:
          - containerPort: 5000
        volumeMounts:
          - name: detail-server
            mountPath: /var/static
      volumes:
        - name: detail-server
          configMap:
            name: detail-server
---

apiVersion: v1
kind: Service
metadata:
  name: detail-service
  namespace: sample-sms
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: detail
