apiVersion: v1
kind: ConfigMap
metadata:
  name: rating-server
  namespace: sample-sms
data:
  server: |
    from flask import Flask, json
    api = Flask(__name__)
    @api.route('/', methods=['GET'])
    def get():
      rating = [{"id": 1, "name": "Rating One"}, {"id": 2, "name": "Rating Two"}]
      return json.dumps(rating)
    if __name__ == '__main__':
      api.run()
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-rating
  namespace: sample-sms
  annotations:
    medinvention.dev/sms.group: rating
    medinvention.dev/sms.port: "5000"
    medinvention.dev/sms.service: rating-service
spec:
  selector:
    matchLabels:
      app: rating
  replicas: 1
  template:
    metadata:
      labels:
        app: rating
    spec:
      containers:
      - name: server
        image: python:3
        command: ['sh', '-c', 'pip install flask && python /var/static/server']
        ports:
          - containerPort: 5000
        volumeMounts:
          - name: rating-server
            mountPath: /var/static
      volumes:
        - name: rating-server
          configMap:
            name: rating-server
---

apiVersion: v1
kind: Service
metadata:
  name: rating-service
  namespace: sample-sms
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: rating
