apiVersion: v1
kind: ConfigMap
metadata:
  name: review-v3-server
  namespace: sample-sms
data:
  server: |
    from flask import Flask, json
    import requests
    api = Flask(__name__)
    @api.route('/', methods=['GET'])
    def get():
      rating = requests.get('http://rating-service.sample-sms.svc.cluster.local:5000')
      if rating.status_code != 200:
        raise Error('GET detail {}'.format(rating.status_code))  
      reviews = {"ratings": rating.json(), "rev": "v3", "reviews": [{"id": 1, "name": "Review One"}, {"id": 2, "name": "Review Two"}]}
      return json.dumps(reviews)
    if __name__ == '__main__':
      api.run()
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-review-v3
  namespace: sample-sms
  annotations:
    medinvention.dev/sms.group: review
    medinvention.dev/sms.port: "5000"
    medinvention.dev/sms.service: review-v3-service
spec:
  selector:
    matchLabels:
      app: review-v3
  replicas: 1
  template:
    metadata:
      labels:
        app: review-v3
    spec:
      containers:
      - name: server
        image: python
        command: ['sh', '-c', 'pip install flask requests && python /var/static/server']
        ports:
          - containerPort: 5000
        volumeMounts:
          - name: review-v3-server
            mountPath: /var/static
      volumes:
        - name: review-v3-server
          configMap:
            name: review-v3-server
---

apiVersion: v1
kind: Service
metadata:
  name: review-v3-service
  namespace: sample-sms
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: review-v3
